# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefacto',
            fields=[
                ('id_artefacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mostrar', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('ruta', models.FileField(null=True, upload_to='files')),
                ('fecha_hora_carga', models.DateTimeField()),
                ('fecha_hora_edicion', models.DateTimeField()),
                ('reusable', models.BooleanField(default=False)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=150)),
                ('descripccion', models.CharField(max_length=1000)),
                ('ubicacion', models.CharField(blank=True, max_length=1000)),
                ('fecha_creacion', models.DateField()),
                ('reusable', models.BooleanField(default=False)),
                ('id_proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Proyecto')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Usuario')),
            ],
        ),
    ]
