# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='artefacto',
            field=models.ManyToManyField(to='polls.Artefacto'),
        ),
        migrations.AlterField(
            model_name='artefacto',
            name='cargado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
