# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181013_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefacto',
            name='id_recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Recurso'),
        ),
    ]
