# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_artefacto_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefacto',
            name='ruta',
        ),
        migrations.AddField(
            model_name='artefacto',
            name='archivo',
            field=models.FileField(null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='artefacto',
            name='fecha_hora_edicion',
            field=models.DateTimeField(null=True),
        ),
    ]
