# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_artefacto_id_recurso'),
        ('polls', '0002_auto_20181011_0605'),
    ]

    operations = [
    ]
