# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_merge_20181027_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=1000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('finalizado', models.BooleanField(default=False)),
                ('periodicidad', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id_fase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Actividad')),
                ('id_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAct',
            fields=[
                ('id_tipoact', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='artefacto',
        ),
        migrations.AlterField(
            model_name='dueno',
            name='id_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Area_Usuaria'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Fase'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipoact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.TipoAct'),
        ),
    ]
