# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20181028_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dueno',
            name='id_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Area_Usuaria'),
        ),
    ]
